<?php

  function simplo_events_node_presave($node) {
    if ($node->type == 'simplo_session') {
      if (isset($node->field_time_slot['und'][0]['nid'])) {

        $old_time = $node->original->field_time_slot['und'][0]['nid'];
        $new_time = $node->field_time_slot['und'][0]['nid'];

        // release previous time slot
        if (isset($node->original->field_time_slot['und'][0]['nid'])) {
//          backdrop_set_message($message = "release previous time slot.", $type = 'status', $repeat = TRUE);
          $time_slot = node_load($old_time);
          $time_slot->field_slot_taken['und'][0]['value'] = 0;
          $time_slot->save();
        }
//        backdrop_set_message($message = "claim open time slot.  ", $type = 'status', $repeat = TRUE);

        // claim open time slot
        $time_slot = node_load($new_time);
        $time_slot->field_slot_taken['und'][0]['value'] = 1;
        $time_slot->save();

//        backdrop_set_message($message = $old_time . " changed to " . $new_time, $type = 'status', $repeat = TRUE);
//        backdrop_set_message($message = "Updating scheduled time", $type = 'status', $repeat = TRUE);
        $node->field_scheduled_time['und'][0]['nid'] = $new_time;
      }

      $utcTime = $node->field_date_time['und']['0']['value'];
      $mplsTime = date('D m/j g:i a', strtotime('-5 hours', strtotime($utcTime)));
      $sydneyTime = date('D m/j g:i a', strtotime('+15 hours', strtotime($mplsTime)));
      $sfTime = date('D m/j g:i a', strtotime('-2 hours', strtotime($mplsTime)));
      $newyorkTime = date('D m/j g:i a', strtotime('+1 hours', strtotime($mplsTime)));
      $berlinTime = date('D m/j g:i a', strtotime('+7 hours', strtotime($mplsTime)));
      $dhakaTime = date('D m/j g:i a', strtotime('+11 hours', strtotime($mplsTime)));
      $londonTime = date('D m/j g:i a', strtotime('+6 hours', strtotime($mplsTime)));

      $timedisplay = '<div class="time-zones">';
      $timedisplay = $timedisplay . '<div class="zone even"> <div class="header">Start Time</div></div>';
      $timedisplay = $timedisplay . '<div class="zone odd"> <div class="city">San Francisco, USA</div> <div class="time">' . $sfTime . '</div></div>';
      $timedisplay = $timedisplay . '<div class="zone even"> <div class="city">Chicago, USA</div><div class="city">Lima, Peru</div><div class="time">' . $mplsTime  . '</div></div>';
      $timedisplay = $timedisplay . '<div class="zone odd"> <div class="city">New York, USA </div><div class="time">' . $newyorkTime  . '</div></div>';
      $timedisplay = $timedisplay . '<div class="zone even"> <div class="city">London, UK </div><div class="time">' . $londonTime  . '</div></div>';
      $timedisplay = $timedisplay . '<div class="zone odd"> <div class="city">Berlin, Germany</div><div class="city">Johannesburg, South Africa </div><div class="time">' . $berlinTime  . '</div></div>';
      $timedisplay = $timedisplay . '<div class="zone even"> <div class="city">Dhaka, Bangladesh </div><div class="time">' . $dhakaTime  . '</div></div>';
      $timedisplay = $timedisplay . '<div class="zone odd"> <div class="city">Sydney, Austrailia </div><div class="time">' . $sydneyTime  . '</div></div>';
      $timedisplay = $timedisplay . '</div>';

      $node->field_time_zone_listings['und']['0']['value'] = $timedisplay;
    }
  }

  function simplo_events_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == 'simplo_session_node_form') {
      $form['field_time_zone_listings']['#access'] = 0;
      $form['field_scheduled_time']['#access'] = 0;
      $form['field_time_slot']['#access'] = 0;
      $form['field_discussion_questions']['#access'] = 0;
    }
  }







